NOV26.Protofolio.web/Controllers/PersonalInformationModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NOV26.Protofolio.web.Data;
using NOV26.Protofolio.web.Models;

namespace NOV26.Protofolio.web.Controllers
{
    public class PersonalInformationModelsController : Controller
    {
        private readonly NOV26ProtofoliowebContext _context;

        public PersonalInformationModelsController(NOV26ProtofoliowebContext context)
        {
            _context = context;
        }

        // GET: PersonalInformationModels
        public async Task<IActionResult> Index()
        {
            return _context.PersonalInformationModel != null ?
                        View(await _context.PersonalInformationModel.ToListAsync()) :
                        Problem("Entity set 'NOV26ProtofoliowebContext.PersonalInformationModel'  is null.");
        }

        // GET: PersonalInformationModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PersonalInformationModel == null)
            {
                return NotFound();
            }

            var personalInformationModel = await _context.PersonalInformationModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (personalInformationModel == null)
            {
                return NotFound();
            }

            return View(personalInformationModel);
        }

        // GET: PersonalInformationModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PersonalInformationModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,Title,Summary,Address,DOB,Email,ZipCode,Phone,CompletedProjects,UserPhotoUrl")] PersonalInformationModel personalInformationModel, IFormFile UserPhotoUrl)
        {
            if (UserPhotoUrl != null && UserPhotoUrl.Length > 0)
            {
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads", UserPhotoUrl.FileName);
                //Using Buffering
                using (var stream = System.IO.File.Create(filePath))
                {
                    // The file is saved in a buffer before being processed
                    await UserPhotoUrl.CopyToAsync(stream);
                }
            }
            if (ModelState.IsValid)
            {
                personalInformationModel.UserPhotoUrl = "/uploads/" + UserPhotoUrl.FileName;
                _context.Add(personalInformationModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(personalInformationModel);
        }

        // GET: PersonalInformationModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PersonalInformationModel == null)
            {
                return NotFound();
            }

            var personalInformationModel = await _context.PersonalInformationModel.FindAsync(id);
            if (personalInformationModel == null)
            {
                return NotFound();
            }
            return View(personalInformationModel);
        }

        // POST: PersonalInformationModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,Title,Summary,Address,DOB,Email,ZipCode,Phone,CompletedProjects,UserPhotoUrl")] PersonalInformationModel personalInformationModel)
        {
            if (id != personalInformationModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(personalInformationModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonalInformationModelExists(personalInformationModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(personalInformationModel);
        }

        // GET: PersonalInformationModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PersonalInformationModel == null)
            {
                return NotFound();
            }

            var personalInformationModel = await _context.PersonalInformationModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (personalInformationModel == null)
            {
                return NotFound();
            }

            return View(personalInformationModel);
        }

        // POST: PersonalInformationModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PersonalInformationModel == null)
            {
                return Problem("Entity set 'NOV26ProtofoliowebContext.PersonalInformationModel'  is null.");
            }
            var personalInformationModel = await _context.PersonalInformationModel.FindAsync(id);
            if (personalInformationModel != null)
            {
                _context.PersonalInformationModel.Remove(personalInformationModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonalInformationModelExists(int id)
        {
            return (_context.PersonalInformationModel?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

NOV26.Protofolio.web/Views/Shared/_Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">About</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Links</h2>
                    <ul class="list-unstyled">
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Home</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>About</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Services</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Projects</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Services</h2>
                    <ul class="list-unstyled">
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Design</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Development</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Business Strategy</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Data Analysis</a></li>
                        <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Graphic Design</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
                            <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

NOV26.Protofolio.web/Views/Shared/_Js.cshtml
<script src="/web/js/jquery.min.js"></script>
<script src="/web/js/jquery-migrate-3.0.1.min.js"></script>
<script src="/web/js/popper.min.js"></script>
<script src="/web/js/bootstrap.min.js"></script>
<script src="/web/js/jquery.easing.1.3.js"></script>
<script src="/web/js/jquery.waypoints.min.js"></script>
<script src="/web/js/jquery.stellar.min.js"></script>
<script src="/web/js/owl.carousel.min.js"></script>
<script src="/web/js/jquery.magnific-popup.min.js"></script>
<script src="/web/js/aos.js"></script>
<script src="/web/js/jquery.animateNumber.min.js"></script>
<script src="/web/js/scrollax.min.js"></script>
<script src="/web/js/main.js"></script>

NOV26.Protofolio.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NOV26 Protofolio</title>
    <partial name="_css" />
</head>
<body>
    <partial name="_Nav" />

    @RenderBody()

    <partial name="_Footer" />

    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>

    <partial name="_Js"></partial>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NOV26.Protofolio.web/Views/Shared/_Nav.cshtml
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-navbar-light site-navbar-target" id="ftco-navbar">
	<div class="container">
		<a class="navbar-brand" href="index.html">Clark</a>
		<button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="oi oi-menu"></span> Menu
		</button>

		<div class="collapse navbar-collapse" id="ftco-nav">
			<ul class="navbar-nav nav ml-auto">
				<li class="nav-item"><a href="#home-section" class="nav-link"><span>Home</span></a></li>
				<li class="nav-item"><a href="#about-section" class="nav-link"><span>About</span></a></li>
				<li class="nav-item"><a href="#resume-section" class="nav-link"><span>Resume</span></a></li>
				<li class="nav-item"><a href="#services-section" class="nav-link"><span>Services</span></a></li>
				<li class="nav-item"><a href="#skills-section" class="nav-link"><span>Skills</span></a></li>
				<li class="nav-item"><a href="#projects-section" class="nav-link"><span>Projects</span></a></li>
				<li class="nav-item"><a href="#blog-section" class="nav-link"><span>My Blog</span></a></li>
				<li class="nav-item"><a href="#contact-section" class="nav-link"><span>Contact</span></a></li>
			</ul>
		</div>
	</div>
</nav>

NOV26.Protofolio.web/Views/Shared/_SideBar.cshtml
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
           aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Setup</span>
        </a>
        <div id="collapseTwo" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Components:</h6>
                <a class="collapse-item" asp-controller="PersonalInformationModels" asp-action="Index">Personal Information</a>
                <a class="collapse-item" href="/ResumeModels">Resume</a>
                <a class="collapse-item" href="/ServiceModels">Service</a>
                <a class="collapse-item" href="/SkillModels">Skill</a>
                <a class="collapse-item" href="/ProjectModels">Project</a>
                <a class="collapse-item" href="/BlogModels">Blogs</a>
                <a class="collapse-item" href="/UserModels">Users</a>

            </div>
        </div>
    </li>


</ul>
<!-- End of Sidebar -->

NOV26.Protofolio.web/Views/Shared/_css.cshtml
<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">

<link rel="stylesheet" href="/web/css/open-iconic-bootstrap.min.css">
<link rel="stylesheet" href="/web/css/animate.css">
<link rel="stylesheet" href="/web/css/owl.carousel.min.css">
<link rel="stylesheet" href="/web/css/owl.theme.default.min.css">
<link rel="stylesheet" href="/web/css/magnific-popup.css">
<link rel="stylesheet" href="/web/css/aos.css">
<link rel="stylesheet" href="/web/css/ionicons.min.css">
<link rel="stylesheet" href="/web/css/flaticon.css">
<link rel="stylesheet" href="/web/css/icomoon.css">
<link rel="stylesheet" href="/web/css/style.css">